version: "3.6"
services:
  payment:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      target: dev
    volumes:
      - ./:/go/src
    command: air -c ./air/.air.toml
    ports:
      - 8081:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - IS_DEBUG=${IS_DEBUG}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - rdb

  rdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3307:${DB_PORT}
    volumes:
      - db_store:/var/lib/mysql
      - ./docker/mysql/conf/dev.cnf:/etc/mysql/my.cnf

volumes:
  db_store:
