openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Payment API"

paths:
   /api/invoices:
    post:
      operationId: PostInvoice
      summary: 新規請求書の作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInvoiceRequest'
      responses:
        '200':
          description: 請求書の作成に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostInvoiceResponse'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認可エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      operationId: GetInvoices
      summary: 請求書の一覧取得
      parameters:
        - name: dueFrom
          in: query
          description: 取得する請求書の開始日時
          required: false
          schema:
            type: string
        - name: dueTo
          in: query
          description: 取得する請求書の終了日時
          required: false
          schema:
            type: string  
        - name: page
          in: query
          description: ページ
          required: false
          schema:
            type: integer
        - name: containsDeleted
          in: query
          description: 削除済みを含むか
          required: false
          schema:
            type: boolean

      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetInvoicesResponse'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: エラー内容

    PostInvoiceRequest:
      type: object
      required:
        - paymentAmount
        - dueAt
        - clientId
      properties:
        paymentAmount:
          type: integer
          minimum: 1
          description: 支払金額
        dueAt:
          type: string
          description: 支払期日
        clientId:
          type: string
          description: 取引先ID

    PostInvoiceResponse:
      type: object
      required:
        - invoiceId 
        - companyId
        - issueDate
        - paymentAmount
        - fee
        - tax
        - invoiceAmount
        - dueDate
      properties:
        invoiceId:
          type: string
          discription: 請求書ID
        companyId:
          type: string
          discription: 企業ID
        issueDate:
          type: string
          discription: 発行日
        paymentAmount:
          type: integer
          discription: 支払い金額 
        fee:
          type: integer
          discription: 手数料 
        tax: 
          type: integer
          discription: 税金額
        invoiceAmount:
          type: integer
          discription: 請求金額
        dueDate:
          type: string
          discription: 支払日

    GetInvoicesResponse:
      type: object
      required:
        - list
      properties:
        list: 
          type: array
          items:
            $ref: '#/components/schemas/InvoiceListResponse'
    InvoiceListResponse:
      type: object
      required:
        - invoiceId 
        - companyId
        - issueDate
        - dueDate
        - paymentAmount
        - fee
        - feeRate
        - tax
        - taxRate
        - invoiceAmount
        - updatedAt
        - deletedAt
        - client
        - statusLogs
      properties:
        invoiceId:
          type: string
          discription: 請求書ID
        companyId:
          type: string
          discription: 企業ID
        issueDate:
          type: string
          discription: 発行日
        dueDate:
          type: string
          discription: 支払日
        paymentAmount:
          type: integer
          discription: 支払い金額 
        fee:
          type: integer
          discription: 手数料 
        feeRate:
          type: string
          discription: 手数料%表記
        tax: 
          type: integer
          discription: 税金額
        taxRate: 
          type: string
          discription: 税金額%表記
        invoiceAmount:
          type: integer
          discription: 請求金額
        updatedAt:
          type: string
          description: 更新日時
        deletedAt:
          type: string
          description: 削除日時
        client:
          $ref: '#/components/schemas/Client'
        statusLogs:
          type: array
          items:
            $ref: '#/components/schemas/StatusLog'
    Client:
      type: object
      required: 
        - companyId
        - name
      properties:
        companyId:
          type: string
          description: 企業ID
        name:
          type: string
          description: クライアント名
    StatusLog:
      type: object
      required: 
        - userName
        - status
        - createdAt
        - updatedAt
        - deletedAt
      properties:
        userName:
          type: string
          description: ステータス変更者名
        status:
          type: string
          description: 現在の状態
        createdAt:
          type: string
          description: 作成日
        updatedAt:
          type: string
          description: 変更日
        deletedAt:
          type: string
          description: 削除日

              

