// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package handler

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message エラー内容
	Message string `json:"message"`
}

// GetInvoicesResponse defines model for GetInvoicesResponse.
type GetInvoicesResponse = []struct {
	CompanyId     string `json:"companyId"`
	DueDate       string `json:"dueDate"`
	Fee           int    `json:"fee"`
	InvoiceAmount int    `json:"invoiceAmount"`
	InvoiceId     string `json:"invoiceId"`
	IssueDate     string `json:"issueDate"`
	PaymentAmount int    `json:"paymentAmount"`
	Tax           int    `json:"tax"`
}

// PostInvoiceRequest defines model for PostInvoiceRequest.
type PostInvoiceRequest struct {
	// ClientId 取引先ID
	ClientId string `json:"clientId"`

	// DueAt 支払期日
	DueAt string `json:"dueAt"`

	// PaymentAmount 支払金額
	PaymentAmount int `json:"paymentAmount"`
}

// PostInvoiceResponse defines model for PostInvoiceResponse.
type PostInvoiceResponse struct {
	CompanyId     string `json:"companyId"`
	DueDate       string `json:"dueDate"`
	Fee           int    `json:"fee"`
	InvoiceAmount int    `json:"invoiceAmount"`
	InvoiceId     string `json:"invoiceId"`
	IssueDate     string `json:"issueDate"`
	PaymentAmount int    `json:"paymentAmount"`
	Tax           int    `json:"tax"`
}

// GetInvoicesParams defines parameters for GetInvoices.
type GetInvoicesParams struct {
	// FromDatetime 取得する請求書の開始日時
	FromDatetime *string `form:"fromDatetime,omitempty" json:"fromDatetime,omitempty"`

	// ToDatetime 取得する請求書の終了日時
	ToDatetime *string `form:"toDatetime,omitempty" json:"toDatetime,omitempty"`
}

// PostInvoiceJSONRequestBody defines body for PostInvoice for application/json ContentType.
type PostInvoiceJSONRequestBody = PostInvoiceRequest
