// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package handler

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message エラー内容
	Message string `json:"message"`
}

// GetInvoicesResponse defines model for GetInvoicesResponse.
type GetInvoicesResponse struct {
	List []InvoiceListResponse `json:"list"`
}

// InvoiceListResponse defines model for InvoiceListResponse.
type InvoiceListResponse struct {
	CompanyId string `json:"companyId"`

	// DeletedAt 削除日時
	DeletedAt     string `json:"deletedAt"`
	DueDate       string `json:"dueDate"`
	Fee           int    `json:"fee"`
	FeeRate       string `json:"feeRate"`
	InvoiceAmount int    `json:"invoiceAmount"`
	InvoiceId     string `json:"invoiceId"`
	IssueDate     string `json:"issueDate"`
	PaymentAmount int    `json:"paymentAmount"`
	Tax           int    `json:"tax"`
	TaxRate       string `json:"taxRate"`

	// UpdatedAt 更新日時
	UpdatedAt string `json:"updatedAt"`
}

// PostInvoiceRequest defines model for PostInvoiceRequest.
type PostInvoiceRequest struct {
	// ClientId 取引先ID
	ClientId string `json:"clientId"`

	// DueAt 支払期日
	DueAt string `json:"dueAt"`

	// PaymentAmount 支払金額
	PaymentAmount int `json:"paymentAmount"`
}

// PostInvoiceResponse defines model for PostInvoiceResponse.
type PostInvoiceResponse struct {
	CompanyId     string `json:"companyId"`
	DueDate       string `json:"dueDate"`
	Fee           int    `json:"fee"`
	InvoiceAmount int    `json:"invoiceAmount"`
	InvoiceId     string `json:"invoiceId"`
	IssueDate     string `json:"issueDate"`
	PaymentAmount int    `json:"paymentAmount"`
	Tax           int    `json:"tax"`
}

// GetInvoicesParams defines parameters for GetInvoices.
type GetInvoicesParams struct {
	// DueFrom 取得する請求書の開始日時
	DueFrom *string `form:"dueFrom,omitempty" json:"dueFrom,omitempty"`

	// DueTo 取得する請求書の終了日時
	DueTo *string `form:"DueTo,omitempty" json:"DueTo,omitempty"`

	// Page ページ
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// ContainsDeleted 削除済みを含むか
	ContainsDeleted *bool `form:"containsDeleted,omitempty" json:"containsDeleted,omitempty"`
}

// PostInvoiceJSONRequestBody defines body for PostInvoice for application/json ContentType.
type PostInvoiceJSONRequestBody = PostInvoiceRequest
